### ISSUE TITLE
status update delayed, possible deadlock

### ISSUE THREAD

**Issue by CensorKao** [livekit/livekit-server#587]
**Describe the bug**
@davidzhao @boks1971 @frostbyte73 
2022-04-03T08:32:51.546Z	ERROR	livekit	logger/logger.go:34	status update delayed, possible deadlock	{"delay": 12, "goroutines": "goroutine 97 [running]:\nruntime/pprof.writeGoroutineStacks({0x109d000, 0xc0347404e0})\n\t/usr/local/go/src/runtime/pprof/pprof.go:693 +0x70\nruntime/pprof.writeGoroutine({0x109d000, 0xc0347404e0}, 0xc0002c5000)\n\t/usr/local/go/src/runtime/pprof/pprof.go:682 +0x2b\nruntime/pprof.(*Profile).WriteTo(0xf6f5bc, {0x109d000, 0xc0347404e0}, 0xc0002bd880)\n\t/usr/local/go/src/runtime/pprof/pprof.go:331 +0x14b\ngithub.com/livekit/livekit-server/pkg/routing.(*RedisRouter).statsWorker(0xc00013e480)\n\t/workspace/pkg/routing/redisrouter.go:363 +0x2aa\ncreated by github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).Start\n\t/workspace/pkg/routing/redisrouter.go:284 +0x85\n\ngoroutine 1 [chan receive, 2058 minutes]:\ngithub.com/livekit/livekit-server/pkg/service.(*LivekitServer).Start(0xc000b1b5e0)\n\t/workspace/pkg/service/server.go:208 +0x2d6\nmain.startServer(0xc00027cc40)\n\t/workspace/cmd/server/main.go:215 +0x41c\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc0001d1860, {0x10b66a8, 0xc0000381e0}, {0xc0000300a0, 0x5, 0x5})\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x7a8\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224\nmain.main()\n\t/workspace/cmd/server/main.go:144 +0xcef\n\ngoroutine 25 [select]:\ngithub.com/livekit/livekit-server/pkg/telemetry.(*telemetryService).run(0xc00011cfa8)\n\t/workspace/pkg/telemetry/telemetryservice.go:61 +0x91\ncreated by github.com/livekit/livekit-server/pkg/telemetry.NewTelemetryService\n\t/workspace/pkg/telemetry/telemetryservice.go:53 +0x1a5\n\ngoroutine 10 [select]:\ngithub.com/go-redis/redis/v8/internal/pool.(*ConnPool).reaper(0xc0002f0960, 0x0)\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/internal/pool/pool.go:463 +0xda\ncreated by github.com/go-redis/redis/v8/internal/pool.NewConnPool\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/internal/pool/pool.go:111 +0x229\n\ngoroutine 24 [select]:\ngithub.com/gammazero/workerpool.(*WorkerPool).dispatch(0xc00012c100)\n\t/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:184 +0x128\ncreated by github.com/gammazero/workerpool.New\n\t/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:37 +0x147\n\ngoroutine 16 [IO wait, 841 minutes]:\ninternal/poll.runtime_pollWait(0x7fcf85e638a0, 0x72)\n\t/usr/local/go/src/runtime/netpoll.go:234 +0x89\ninternal/poll.(*pollDesc).wait(0xc00012c580, 0xc000041000, 0x0)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:89\ninternal/poll.(*FD).Accept(0xc00012c580)\n\t/usr/local/go/src/internal/poll/fd_unix.go:402 +0x22c\nnet.(*netFD).accept(0xc00012c580)\n\t/usr/local/go/src/net/fd_unix.go:173 +0x35\nnet.(*TCPListener).accept(0xc000302030)\n\t/usr/local/go/src/net/tcpsock_posix.go:140 +0x28\nnet.(*TCPListener).Accept(0xc000302030)\n\t/usr/local/go/src/net/tcpsock.go:262 +0x3d\ngithub.com/pion/ice/v2.(*TCPMuxDefault).start(0xc0002d9800)\n\t/go/pkg/mod/github.com/pion/ice/v2@v2.2.2/tcp_mux.go:91 +0xdd\ngithub.com/pion/ice/v2.NewTCPMuxDefault.func1()\n\t/go/pkg/mod/github.com/pion/ice/v2@v2.2.2/tcp_mux.go:82 +0x5a\ncreated by github.com/pion/ice/v2.NewTCPMuxDefault\n\t/go/pkg/mod/github.com/pion/ice/v2@v2.2.2/tcp_mux.go:80 +0x18f\n\ngoroutine 81 [syscall, 2058 minutes]:\nos/signal.signal_recv()\n\t/usr/local/go/src/runtime/sigqueue.go:169 +0x98\nos/signal.loop()\n\t/usr/local/go/src/os/signal/signal_unix.go:24 +0x19\ncreated by os/signal.Notify.func1.1\n\t/usr/local/go/src/os/signal/signal.go:151 +0x2c\n\ngoroutine 70 [chan receive, 2058 minutes]:\nmain.startServer.func2()\n\t/workspace/cmd/server/main.go:210 +0x35\ncreated by main.startServer\n\t/workspace/cmd/server/main.go:209 +0x40f\n\ngoroutine 98 [semacquire]:\nsync.runtime_SemacquireMutex(0x1786a30, 0x28, 0x44d4f4)\n\t/usr/local/go/src/runtime/sema.go:71 +0x25\nsync.(*Mutex).lockSlow(0xc03459cd90)\n\t/usr/local/go/src/sync/mutex.go:138 +0x165\nsync.(*Mutex).Lock(...)\n\t/usr/local/go/src/sync/mutex.go:81\nsync.(*RWMutex).Lock(0xe34320)\n\t/usr/local/go/src/sync/rwmutex.go:111 +0x36\ngithub.com/pion/webrtc/v3.(*PeerConnection).Close(0xc03459cd80)\n\t/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.27/peerconnection.go:1957 +0x12c\ngithub.com/livekit/livekit-server/pkg/rtc.(*PCTransport).Close(0xc032d05480)\n\t/workspace/pkg/rtc/transport.go:248 +0x37\ngithub.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).Close(0xc033714300, 0x10)\n\t/workspace/pkg/rtc/participant.go:575 +0x490\ngithub.com/livekit/livekit-server/pkg/rtc.(*Room).RemoveParticipant(0xc0313b2380, {0xc033edcc26, 0x5})\n\t/workspace/pkg/rtc/room.go:336 +0x28c\ngithub.com/livekit/livekit-server/pkg/service.(*RoomManager).StartSession(0xc00012c600, {0x10b6670, 0xc000145440}, {0xc0340186fa, 0xc03490dd30}, {{0xc034018710, 0x5}, {0x0, 0x0}, 0x0, ...}, ...)\n\t/workspace/pkg/service/roommanager.go:208 +0x518\ngithub.com/livekit/livekit-server/pkg/routing.(*RedisRouter).startParticipantRTC(0xc00013e480, 0xc0348827e0, {0xc034018700, 0xc})\n\t/workspace/pkg/routing/redisrouter.go:268 +0x503\ngithub.com/livekit/livekit-server/pkg/routing.(*RedisRouter).handleRTCMessage(0xc00013e480, 0xc03469aa50)\n\t/workspace/pkg/routing/redisrouter.go:459 +0x65\ngithub.com/livekit/livekit-server/pkg/routing.(*RedisRouter).redisWorker(0xc00013e480, 0x0)\n\t/workspace/pkg/routing/redisrouter.go:414 +0x3e8\ncreated by github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).Start\n\t/workspace/pkg/routing/redisrouter.go:285 +0xde\n\ngoroutine 73 [select]:\ngithub.com/go-redis/redis/v8.(*channel).initHealthCheck.func1()\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/pubsub.go:536 +0xf1\ncreated by github.com/go-redis/redis/v8.(*channel).initHealthCheck\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/pubsub.go:530 +0xc8\n\ngoroutine 74 [IO wait]:\ninternal/poll.runtime_pollWait(0x7fcf85e637b8, 0x72)\n\t/usr/local/go/src/runtime/netpoll.go:234 +0x89\ninternal/poll.(*pollDesc).wait(0xc0007f4080, 0xc0018fd000, 0x0)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:89\ninternal/poll.(*FD).Read(0xc0007f4080, {0xc0018fd000, 0x1000, 0x1000})\n\t/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a\nnet.(*netFD).Read(0xc0007f4080, {0xc0018fd000, 0xa, 0xc00131bc88})\n\t/usr/local/go/src/net/fd_posix.go:56 +0x29\nnet.(*conn).Read(0xc000124710, {0xc0018fd000, 0x0, 0x7fcf83263a20})\n\t/usr/local/go/src/net/net.go:183 +0x45\nbufio.(*Reader).fill(0xc0003227e0)\n\t/usr/local/go/src/bufio/bufio.go:101 +0x103\nbufio.(*Reader).ReadSlice(0xc0003227e0, 0x0)\n\t/usr/local/go/src/bufio/bufio.go:360 +0x2f\ngithub.com/go-redis/redis/v8/internal/proto.(*Reader).readLine(0xc00069ce60)\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/internal/proto/reader.go:73 +0x30\ngithub.com/go-redis/redis/v8/internal/proto.(*Reader).ReadLine(0x0)\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/internal/proto/reader.go:59 +0x19\ngithub.com/go-redis/redis/v8/internal/proto.(*Reader).ReadReply(0xc08a74cc1884e526, 0xfb3b88)\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/internal/proto/reader.go:97 +0x2a\ngithub.com/go-redis/redis/v8.(*Cmd).readReply(...)\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/command.go:319\ngithub.com/go-redis/redis/v8.(*PubSub).ReceiveTimeout.func1(0xc000124710)\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/pubsub.go:370 +0x2d\ngithub.com/go-redis/redis/v8/internal/pool.(*Conn).WithReader(0xc00087f900, {0x10b66a8, 0xc0000381e8}, 0x93db92129341, 0xc00131bef8)\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/internal/pool/conn.go:70 +0x6e\ngithub.com/go-redis/redis/v8.(*PubSub).ReceiveTimeout(0xc000b22000, {0x10b66a8, 0xc0000381e8}, 0x0)\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/pubsub.go:369 +0xfe\ngithub.com/go-redis/redis/v8.(*PubSub).Receive(...)\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/pubsub.go:385\ngithub.com/go-redis/redis/v8.(*channel).initMsgChan.func1()\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/pubsub.go:565 +0x9c\ncreated by github.com/go-redis/redis/v8.(*channel).initMsgChan\n\t/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.3/pubsub.go:559 +0xcf\n\ngoroutine 75 [select, 2058 minutes]:\ngithub.com/livekit/livekit-server/pkg/service.(*EgressService).resultsWorker(0xc0001362d0)\n\t/workspace/pkg/service/egress.go:233 +0x114\ncreated by github.com/livekit/livekit-server/pkg/service.(*EgressService).Start\n\t/workspace/pkg/service/egress.go:38 +0x65\n\ngoroutine 76 [select, 2058 minutes]:\ngithub.com/livekit/livekit-server/pkg/service.(*RecordingService).resultsWorker(0xc000127440)\n\t/workspace/pkg/service/recordingservice.go:154 +0x114\ncreated by github.com/livekit/livekit-server/pkg/service.(*RecordingService).Start\n\t/workspace/pkg/service/recordingservice.go:33 +0x65\n\ngoroutine 101 [chan receive, 2058 minutes]:\nreflect.chanrecv(0xc000357fb0, 0x18, 0xc000174900)\n\t/usr/local/go/src/runtime/chan.go:718 +0x25\nreflect.Value.recv({0xdbc600, 0xc000714360, 0xc0000381e8}, 0xd0)\n\t/usr/local/go/src/reflect/value.go:1874 +0x130\nreflect.Value.Recv({0xdbc600, 0xc000714360, 0xc0001749c0})\n\t/usr/local/go/src/reflect/value.go:1854 +0x6f\ngithub.com/eapache/channels.Wrap.func1()\n\t/go/pkg/mod/github.com/eapache/channels@v1.1.0/channels.go:244 +0xfb\ncreated by github.com/eapache/channels.Wrap\n\t/go/pkg/mod/github.com/eapache/channels@v1.1.0/channels.go:241 +0xfd\n\ngoroutine 3659586 [chan receive, 829 minutes]:\ngithub.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine.func1()\n\t/go/pkg/mod/github.com/pion/ice/v2@v2.2.2/agent.go:413 +0x48\ncreated by github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine\n\t/go/pkg/mod/github.com/pion/ice/v2@v2.2.2/agent.go:409 +0x5f\n\ngoroutine 77 [IO wait, 2058 minutes]:\ninternal/poll.runtime_pollWait(0x7fcf85e63418, 0x72)\n\t/usr/local/go/src/runtime/netpoll.go:234 +0x89\ninternal/poll.(*pollDesc).wait(0xc000450d80, 0x4, 0x0)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:89\ninternal/poll.(*FD).Accept(0xc000450d80)\n\t/usr/local/go/src/internal/poll/fd_unix.go:402 +0x22c\nnet.(*netFD).accept(0xc000450d80)\n\t/usr/local/go/src/net/fd_unix.go:173 +0x35\nnet.(*TCPListener).accept(0xc000302d38)\n\t/usr/local/go/src/net/tcpsock_posix.go:140 +0x28\nnet.(*TCPListener).Accept(0xc000302d38)\n\t/usr/local/go/src/net/tcpsock.go:262 +0x3d\nnet/http.(*Server).Serve(0xc0002ce2a0, {0x10af818, 0xc000302d38})\n\t/usr/local/go/src/net/http/server.go:3002 +0x394\ngithub.com/livekit/livekit-server/pkg/service.(*LivekitServer).Start.func2()\n\t/workspace/pkg/service/server.go:167 +0x29\ncreated by github.com/livekit/livekit-server/pkg/service.(*LivekitServer).Start\n\t/workspace/pkg/service/server.go:166 +0x1ef\n\ngoroutine 78 [IO wait]:\ninternal/poll.runtime_pollWait(0x7fcf85e63500, 0x72)\n\t/usr/local/go/src/runtime/netpoll.go:234 +0x89\ninternal/poll.(*pollDesc).wait(0xc000450d00, 0xc00006b800, 0x0)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:89\ninternal/poll.(*FD).Accept(0xc000450d00)\n\t/usr/local/go/src/internal/poll/fd_unix.go:402 +0x22c\nnet.(*netFD).accept(0xc000450d00)\n\t/usr/local/go/src/net/fd_unix.go:173 +0x35\nnet.(*TCPListener).accept(0xc000302d20)\n\t/usr/local/go/src/net/tcpsock_posix.go:140 +0x28\nnet.(*TCPListener).Accept(0xc000302d20)\n\t/usr/local/go/src/net/tcpsock.go:262 +0x3d\nnet/http.(*Server).Serve(0xc0002ce1c0, {0x10af818, 0xc000302d20})\n\t/usr/local/go/src/net/http/server.go:3002 

.....................................
.....................................

.Enqueue\n\t/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.27"}
github.com/livekit/protocol/logger.Errorw
	/go/pkg/mod/github.com/livekit/protocol@v0.12.0/logger/logger.go:34
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).statsWorker
	/workspace/pkg/routing/redisrouter.go:364
redis: 2022/04/03 08:36:58 pubsub.go:599: redis: &{%!s(*redis.PubSub=&{0xc0002ce0e0 0x9a66c0 0x9a8d60 {0 0} 0xc00087f900 map[rtc_channel:ND_LTD25FgZ:{} signal_channel:ND_LTD25FgZ:{}] map[] false 0xc00032a0c0 0xc000322a20 {1 {0 0}} 0xc001588100 <nil>}) %!s(chan *redis.Message=0xc000322960) %!s(chan interface {}=<nil>) %!s(chan struct {}=0xc0000a4f00) %!s(int=100) %!s(time.Duration=60000000000) %!s(time.Duration=3000000000)} channel is full for 1m0s (message is dropped)
redis: 2022/04/03 08:37:58 pubsub.go:599: redis: &{%!s(*redis.PubSub=&{0xc0002ce0e0 0x9a66c0 0x9a8d60 {0 0} 0xc00087f900 map[rtc_channel:ND_LTD25FgZ:{} signal_channel:ND_LTD25FgZ:{}] map[] false 0xc00032a0c0 0xc000322a20 {1 {0 0}} 0xc001588100 <nil>}) %!s(chan *redis.Message=0xc000322960) %!s(chan interface {}=<nil>) %!s(chan struct {}=0xc0000a4f00) %!s(int=100) %!s(time.Duration=60000000000) %!s(time.Duration=3000000000)} channel is full for 1m0s (message is dropped)
redis: 2022/04/03 08:38:58 pubsub.go:599: redis: &{%!s(*redis.PubSub=&{0xc0002ce0e0 0x9a66c0 0x9a8d60 {0 0} 0xc00087f900 map[rtc_channel:ND_LTD25FgZ:{} signal_channel:ND_LTD25FgZ:{}] map[] false 0xc00032a0c0 0xc000322a20 {1 {0 0}} 0xc001588100 <nil>}) %!s(chan *redis.Message=0xc000322960) %!s(chan interface {}=<nil>) %!s(chan struct {}=0xc0000a4f00) %!s(int=100) %!s(time.Duration=60000000000) %!s(time.Duration=3000000000)} channel is full for 1m0s (message is dropped)
redis: 2022/04/03 08:39:58 pubsub.go:599: redis: &{%!s(*redis.PubSub=&{0xc0002ce0e0 0x9a66c0 0x9a8d60 {0 0} 0xc00087f900 map[rtc_channel:ND_LTD25FgZ:{} signal_channel:ND_LTD25FgZ:{}] map[] false 0xc00032a0c0 0xc000322a20 {1 {0 0}} 0xc001588100 <nil>}) %!s(chan *redis.Message=0xc000322960) %!s(chan interface {}=<nil>) %!s(chan struct {}=0xc0000a4f00) %!s(int=100) %!s(time.Duration=60000000000) %!s(time.Duration=3000000000)} channel is full for 1m0s (message is dropped)
redis: 2022/04/03 08:40:58 pubsub.go:599: redis: &{%!s(*redis.PubSub=&{0xc0002ce0e0 0x9a66c0 0x9a8d60 {0 0} 0xc00087f900 map[rtc_channel:ND_LTD25FgZ:{} signal_channel:ND_LTD25FgZ:{}] map[] false 0xc00032a0c0 0xc000322a20 {1 {0 0}} 0xc001588100 <nil>}) %!s(chan *redis.Message=0xc000322960) %!s(chan interface {}=<nil>) %!s(chan struct {}=0xc0000a4f00) %!s(int=100) %!s(time.Duration=60000000000) %!s(time.Duration=3000000000)} channel is full for 1m0s (message is dropped)

My redis server command:
docker run -d --restart=always --name rtc-redis -p 6379:6379 redis

Clients can't connect as a new participant, even can't connect to signal. This error does not occur at the beginning, but at peak hours. I have removed redis configurations as a temporary solution.

**Server**
- Version: [0.15.6]
- Environment: [docker]

**Comment by davidzhao** [comment]
Thank you for sending these in. Do you have any repro steps?

Also, looks like this isn't the full logs (only a few goroutines were visible). Are there more logs? If you can attach the full logs as a file, that'd be really helpful in tracking this down.

**Comment by CensorKao** [comment]
> Thank you for sending these in. Do you have any repro steps?
> 
> 
> 
> Also, looks like this isn't the full logs (only a few goroutines were visible). Are there more logs? If you can attach the full logs as a file, that'd be really helpful in tracking this down.
> 
> 

Full logs is too long,so only head and tail pieces pasted.
I forgot to save full logs before delete and restart livekit container. Also can't reproduce it,Cuz this happened in production environment. Next,i want to know how to save error logs only when using docker? I set log level to warning in livekit.yaml,but get info outping from docker logs console.

**Comment by davidzhao** [comment]
Got it, thank you for the details.

You should be able to set log_level [here](https://github.com/livekit/livekit-server/blob/master/config-sample.yaml#L87). If that's not working, can you share part of your config.yaml? (with keys/hostnames redacted)

**Comment by CensorKao** [comment]
> Got it, thank you for the details.
> 
> You should be able to set log_level [here](https://github.com/livekit/livekit-server/blob/master/config-sample.yaml#L87). If that's not working, can you share part of your config.yaml? (with keys/hostnames redacted)

Below is my livekit.yaml config. Please check if there is anything wrong with the configuration. Thanks.

# main TCP port for RoomService and RTC endpoint
# for production setups, this port should be placed behind a load balancer with TLS
port: 7880

# when redis is set, LiveKit will automatically operate in a fully distributed fashion
# clients could connect to any node and be routed to the same room
#redis:
#  address: 192.168.122.25:6379
#  db: 1
  # username: myuser
  # password: mypassword

# WebRTC configuration
rtc:
  # UDP ports to use for client traffic.
  # this port range should be open for inbound traffic on the firewall
  port_range_start: 10000
  port_range_end: 14000
  # when set, LiveKit enable WebRTC ICE over TCP when UDP isn't available
  # this port *cannot* be behind load balancer or TLS, and must be exposed on the node
  # WebRTC transports are encrypted and do not require additional encryption
  # only 80/443 on public IP are allowed if less than 1024
  tcp_port: 7881
  # when set to true, attempts to discover the host's public IP via STUN
  # this is useful for cloud environments such as AWS & Google where hosts have an internal IP
  # that maps to an external one
  use_external_ip: true
  # when set, LiveKit will attempt to use a UDP mux so all UDP traffic goes through
  # a single port. This simplifies deployment, but mux will become an overhead for
  # highly trafficked deployments.
  # port_range_start & end must not be set for this config to take effect
  # udp_port: 7882
  # optional settings
  # # when using REMB, the max bitrate that the SFU would accept, defaults to 3Mbps
  max_bitrate: 3145728
  # # number of packets to buffer in the SFU, defaults to 500
  packet_buffer_size: 500
  # # optional STUN servers for LiveKit clients to use. Clients will be configured to use these STUN servers automatically.
  # # by default LiveKit clients use Google's public STUN servers
  stun_servers:
    - stun.l.google.com:19302
    #- stun1.l.google.com:19302
    #- stun2.l.google.com:19302
    #- stun.stunprotocol.org:3478
  # # optional TURN servers for clients. This isn't necessary if using embedded TURN server (see below).
  turn_servers:
     - host: eu-turn-xxx.xxx.com
       port: 443
  #     # tls, tcp, or udp
       protocol: tls
       username: "xxxxx"
       credential: "xxxxxxx"
  # # allows LiveKit to monitor congestion when sending streams and automatically
  # # manage bandwidth utilization to avoid congestion/loss. Enabled by default
  # congestion_control:
  #   enabled: true
  #   # in the unlikely event of highly congested networks, SFU may choose to pause some tracks
  #   # in order to allow others to stream smoothly. You can disable this behavior here
  #   allow_pause: true
  # # minimum amount of time between pli/fir rtcp packets being sent to an individual
  # # producer. Increasing these times can lead to longer black screens when new participants join,
  # # while reducing them can lead to higher stream bitrate.
  # pli_throttle:
  #   low_quality: 500ms
  #   mid_quality: 1s
  #   high_quality: 1s
  interfaces:
    includes:
      - ens3
    excludes:
      - docker0

# when enabled, LiveKit will expose prometheus metrics on :6789/metrics
prometheus_port: 6789

# API key / secret pairs.
# Keys are used for JWT authentication, server APIs would require a keypair in order to generate access tokens
# and make calls to the server
keys:
  xxxxx: xxxxx

#Logging config
logging:
#   # log level, valid values: debug, info, warning, error
    level: warning
#   # log level for pion, default error
    pion_level: error
#   # when set to true, emit json fields
#   json: false
#   # for production setups, enables sampling algorithm
#   # https://github.com/uber-go/zap/blob/master/FAQ.md#why-sample-application-logs
#   sample: false


# Default room config
# Each room created will inherit these settings. If rooms are created explicitly with CreateRoom, they will take
# precedence over defaults
room:
#   # allow rooms to be automatically created when participants join, defaults to true
    auto_create: true
#   # number of seconds to leave a room open when it's empty
    empty_timeout: 60
#   # limit number of participants that can be in a room, 0 for no limit
    max_participants: 2
#   # only accept specific codecs for clients publishing to this room
#   # this is useful to standardize codecs across clients
#   # other supported codecs are video/h264, video/vp9
    enabled_codecs:
      - mime: audio/opus
      - mime: video/vp8
#   # allow tracks to be unmuted remotely, defaults to false
#   # tracks can always be muted from the Room Service APIs
    enable_remote_unmute: true

# Webhooks
# when configured, LiveKit notifies your URL handler with room events
webhook:
#   # the API key to use in order to sign the message
#   # this must match one of the keys LiveKit is configured with
    api_key: xxxxx
#   # list of URLs to be notified of room events
    urls:
      - https://xx.xxx.com/xxx/livekit

# customize audio level sensitivity
# audio:
#   # minimum level to be considered active, 0-127, where 0 is loudest
#   # defaults to 30
#   active_level: 30
#   # percentile to measure, a participant is considered active if it has exceeded the
#   # ActiveLevel more than MinPercentile% of the time
#   # defaults to 40
#   min_percentile: 40
#   # frequency in ms to notify changes to clients, defaults to 500
#   update_interval: 500
#   # to prevent speaker updates from too jumpy, smooth out values over N samples
#   smooth_intervals: 4

# Region of the current node. Required if using regionaware node selector
# region: us-west-2

# # node selector
# node_selector:
#   # default: random. valid values: random, sysload, regionaware
#   kind: sysload
#   # used in sysload and regionaware
#   # do not assign room to node if load per CPU exceeds sysload_limit
#   sysload_limit: 0.7
#   # used in regionaware
#   # list of regions and their lat/lon coordinates
#   regions:
#     - name: us-west-2
#       lat: 44.19434095976287
#       lon: -123.0674908379146

# # node limits
# # set to -1 to disable a limit
# limit:
#   # defaults to 400 tracks in & out per CPU, up to 8000
#   num_tracks: -1
#   # defaults to 1 GB/s, or just under 10 Gbps
#   bytes_per_sec: 1_000_000_000

**Comment by CensorKao** [comment]
@davidzhao 

After running for 24 hours without redis in production environment, there was another error.

ERROR	livekit	rtc/signalhandler.go:15	could not handle offer.

Please check attachment log files.

[likekit-errors-log.txt](https://github.com/livekit/livekit-server/files/8407603/likekit-errors-log.txt)

**Comment by davidzhao** [comment]
Another user has provided a useful log https://pastebin.com/raw/s9Wmb2f7

It's difficult to tell if you are hitting the exact issue (due to incomplete logs)

The root cause for the known lock issue is when a user connected via TCP and the connection has stalled while server is proceeding with its termination sequence. Fixing coming up.
